"""add function_name to problems and problem_templates table

Revision ID: 3ee6165e9f37
Revises: 6fd417f75ec6
Create Date: 2026-02-12 21:04:16.523818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ee6165e9f37'
down_revision: Union[str, Sequence[str], None] = '6fd417f75ec6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('problem_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.Column('boilerplate_code', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('problem_id', 'language_id', name='uq_problem_language')
    )
    op.create_index(op.f('ix_problem_templates_id'), 'problem_templates', ['id'], unique=False)
    op.create_index(op.f('ix_problem_templates_language_id'), 'problem_templates', ['language_id'], unique=False)
    op.create_index(op.f('ix_problem_templates_problem_id'), 'problem_templates', ['problem_id'], unique=False)
    op.add_column('problems', sa.Column('function_name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('problems', 'function_name')
    op.drop_index(op.f('ix_problem_templates_problem_id'), table_name='problem_templates')
    op.drop_index(op.f('ix_problem_templates_language_id'), table_name='problem_templates')
    op.drop_index(op.f('ix_problem_templates_id'), table_name='problem_templates')
    op.drop_table('problem_templates')
    # ### end Alembic commands ###
