"""add profile and stats fields to user

Revision ID: b1549a2c8c7f
Revises: ba81b115117e
Create Date: 2025-11-28 01:27:17.587274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1549a2c8c7f'
down_revision: Union[str, Sequence[str], None] = 'ba81b115117e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.String(), nullable=True))
    op.add_column('users', sa.Column('school', sa.String(), nullable=True))
    op.add_column('users', sa.Column('avatar_url', sa.String(), nullable=True))
    op.add_column('users', sa.Column('languages', sa.String(), nullable=True))
    op.add_column('users', sa.Column('xp', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('streak', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('problems_solved', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'problems_solved')
    op.drop_column('users', 'streak')
    op.drop_column('users', 'xp')
    op.drop_column('users', 'languages')
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'school')
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###
