"""align_user_solved_and_submission_constraints

Revision ID: ca9d48032795
Revises: 3ee6165e9f37
Create Date: 2026-02-17 16:41:24.462918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca9d48032795'
down_revision: Union[str, Sequence[str], None] = '3ee6165e9f37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_submissions_language_id'), 'submissions', ['language_id'], unique=False)
    op.create_index(op.f('ix_submissions_problem_id'), 'submissions', ['problem_id'], unique=False)
    op.create_index(op.f('ix_submissions_user_id'), 'submissions', ['user_id'], unique=False)
    op.drop_constraint(op.f('submissions_problem_id_fkey'), 'submissions', type_='foreignkey')
    op.drop_constraint(op.f('submissions_user_id_fkey'), 'submissions', type_='foreignkey')
    op.create_foreign_key(None, 'submissions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'submissions', 'problems', ['problem_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_user_solved_problems_problem_id'), 'user_solved_problems', ['problem_id'], unique=False)
    op.create_index(op.f('ix_user_solved_problems_user_id'), 'user_solved_problems', ['user_id'], unique=False)
    op.create_unique_constraint('uq_user_problem', 'user_solved_problems', ['user_id', 'problem_id'])
    op.drop_constraint(op.f('user_solved_problems_user_id_fkey'), 'user_solved_problems', type_='foreignkey')
    op.drop_constraint(op.f('user_solved_problems_problem_id_fkey'), 'user_solved_problems', type_='foreignkey')
    op.create_foreign_key(None, 'user_solved_problems', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_solved_problems', 'problems', ['problem_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_solved_problems', type_='foreignkey')
    op.drop_constraint(None, 'user_solved_problems', type_='foreignkey')
    op.create_foreign_key(op.f('user_solved_problems_problem_id_fkey'), 'user_solved_problems', 'problems', ['problem_id'], ['id'])
    op.create_foreign_key(op.f('user_solved_problems_user_id_fkey'), 'user_solved_problems', 'users', ['user_id'], ['id'])
    op.drop_constraint('uq_user_problem', 'user_solved_problems', type_='unique')
    op.drop_index(op.f('ix_user_solved_problems_user_id'), table_name='user_solved_problems')
    op.drop_index(op.f('ix_user_solved_problems_problem_id'), table_name='user_solved_problems')
    op.drop_constraint(None, 'submissions', type_='foreignkey')
    op.drop_constraint(None, 'submissions', type_='foreignkey')
    op.create_foreign_key(op.f('submissions_user_id_fkey'), 'submissions', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('submissions_problem_id_fkey'), 'submissions', 'problems', ['problem_id'], ['id'])
    op.drop_index(op.f('ix_submissions_user_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_problem_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_language_id'), table_name='submissions')
    # ### end Alembic commands ###
