"""add refresh_token_hash column

Revision ID: e4b30a1bddd6
Revises: 1cce7155f3c5
Create Date: 2025-11-26 22:33:31.395928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4b30a1bddd6'
down_revision: Union[str, Sequence[str], None] = '1cce7155f3c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('refresh_token_hash', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'refresh_token_hash')
    # ### end Alembic commands ###
